# Loki Configuration File
# This tells Loki how to store and manage log data

auth_enabled: false
# No authentication needed for local development

server:
  http_listen_port: 3100
  # Loki will listen on port 3100 inside the container
  
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  # How Loki manages log ingestion
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  # How long to keep chunks of logs

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h
  # Storage schema - how logs are organized in storage

storage_config:
  boltdb:
    directory: /loki/index
  # Where to store the index (metadata about logs)
  filesystem:
    directory: /loki/chunks
  # Where to store actual log data

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  allow_structured_metadata: false
  # Maximum age of logs (7 days)

# WAL configuration for Loki
common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
