
export const SERVICE_ROUTES = {
    USERS: '/api/users',
    COMPANY: '/api/company',
    JOBS: '/api/jobs',
    APPLICATIONS: '/api/applications',
    INTERVIEWS: '/api/interviews',
    OFFERS: '/api/offers',
    NOTIFICATIONS: '/api/notifications',
    CHAT: '/api/chat',
    SUBSCRIPTIONS: '/api/subscriptions'
} as const;

export const ROUTES = {
    authentication: [
        '/api/users/login',
        '/api/users/register', 
        '/api/users/refresh-token',
        '/api/users/admin/login',
        '/api/users/admin/refresh-token',
        '/api/company/login',
        '/api/company/register',
        '/api/company/refresh-token'
    ],

    protected: [
        '/api/users/profile',
        '/api/users/update',
        '/api/users/me',
        '/api/users/logout',
        '/api/users/change-password',
        '/api/users/update-name',
        '/api/users/admin/dashboard/statistics',
        '/api/profile/full',
        '/api/profile',
        '/api/company/profile', 
        '/api/company/update',
        '/api/jobs/create',
        '/api/jobs/update',
        '/api/jobs/delete',
        '/api/jobs/company',
        '/api/jobs/admin/reported', 
        '/api/jobs/:jobId/report',
        '/api/applications/create',
        '/api/applications/update',
        '/api/applications/delete',
        '/api/applications/company/applications',
        '/api/applications/company/statistics',
        '/api/applications/ats/analyze',
        '/api/interviews',
        '/api/offers/template',
        '/api/offers/template/logo',
        '/api/offers/template/signature',
        '/api/offers/template/preview',
        '/api/company/admin/industries',
        '/api/subscriptions', 
        '/api/subscriptions/status', 
        '/api/subscriptions/:subscriptionId/cancel', 
        '/api/subscriptions/:subscriptionId/upgrade', 
        '/api/subscriptions/limits/job-posting', 
        '/api/subscriptions/features/:featureName',
        '/api/admin/subscriptions/plans',
        '/api/admin/subscriptions/plans/:id',
        '/api/admin/subscriptions/plans/:id/price',
        '/api/admin/subscriptions/discounts',
        '/api/admin/subscriptions/discounts/:id',
        '/api/admin/subscriptions/discounts/plan/:planId',
        '/api/admin/subscriptions/revenue',
        '/api/admin/subscriptions/transactions',
        '/api/admin/subscriptions/transactions/sync',
        '/api/settings/logo',
        '/api/settings/company-name',
        '/api/settings/about-page'
    ],
    
    public: [
    '/api/settings', 
        '/api/jobs', 
        '/api/jobs/list',
        '/api/jobs/search',
        '/api/jobs/details',
        '/api/jobs/suggestions',
        '/api/company/list',
        '/api/company/details',
        '/api/users/generate-otp',
        '/api/users/verify-otp',
        '/api/users/resend-otp',
        '/api/users/forgot-password',
        '/api/users/verify-password-reset-otp',
        '/api/users/reset-password',
        '/api/users/google-auth',
        '/api/company/generate-otp',
        '/api/company/verify-otp',
        '/api/company/forgot-password',
        '/api/company/reset-password',
        '/api/industries',
        '/api/subscriptions/plans',
    ]
};