http:
  port: 4000
  host: '0.0.0.0'

admin:
  port: 9876
  host: '0.0.0.0'

logger:
  level: 'debug'
  streams:
    - type: 'stream'
      stream: 'process.stdout'
      level: 'debug'
    - type: 'file'
      path: './logs/gateway.log'
      level: 'debug'

metrics:
  enabled: true
  port: 9090
  host: '0.0.0.0'
  prefix: 'eg_'

redis:
  host: 'redis'
  port: 6379
  db: 0
  options:
    retryDelayOnFailover: 100
    enableReadyCheck: false
    maxRetriesPerRequest: 1
    connectTimeout: 10000
    commandTimeout: 5000
    lazyConnect: true

jwt:
  secretOrKey: 'supersecret'
  issuer: 'job-portal-gateway'
  audience: 'job-portal-users'
  expiresIn: '24h'
  algorithms: ['HS256']
  clockTolerance: 30
  ignoreExpiration: false
  ignoreNotBefore: false
  passRequest: true

cors:
  enabled: true
  origin: 'http://localhost:5173'
  credentials: true
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
  allowedHeaders:
    - Content-Type
    - Authorization
    - x-user-id
    - x-user-email
    - x-user-role

request:
  timeout: 30000
  keepAlive: true
  keepAliveMsecs: 1000

response:
  timeout: 30000

errorHandling:
  enabled: true
  includeStackTrace: false
  logErrors: true

security:
  rateLimit:
    enabled: true
    windowMs: 60000
    max: 100
    message: 'Too many requests from this IP, please try again later.'
  helmet:
    enabled: true
    contentSecurityPolicy: false
    hsts: false

db:
  redis:
    emulate: false
    namespace: "EG"

env:
  NODE_ENV: 'development'
  LOG_LEVEL: 'info'