import { Container } from 'inversify';
import { PrismaClient } from '@prisma/client';
import { IApplicationRepository } from '../repositories/interfaces/IApplicationRepository';
import { ApplicationRepository } from '../repositories/implementations/ApplicationRepository';
import { IApplicationService } from '../services/interfaces/IApplicationService';
import { ApplicationService } from '../services/implementations/ApplicationService';
import { IEventService } from '../services/interfaces/IEventService';
import { KafkaEventService } from '../services/implementations/KafkaEventService';
import { StatusUpdateService } from '../services/implementations/StatusUpdateService';
import { ApplicationController } from '../controllers/ApplicationController';
import { IInterviewRepository } from '../repositories/interfaces/IInterviewRepository';
import { InterviewRepository } from '../repositories/implementations/InterviewRepository';
import { IInterviewService } from '../services/interfaces/IInterviewService';
import { InterviewService } from '../services/implementations/InterviewService';
import { InterviewController } from '../controllers/InterviewController';
import { IUserServiceClient } from '../services/interfaces/IUserServiceClient';
import { UserServiceClient } from '../services/implementations/UserServiceClient';
import { IJobServiceClient } from '../services/interfaces/IJobServiceClient';
import { JobServiceClient } from '../services/implementations/JobServiceClient';
import { IOfferRepository } from '../repositories/interfaces/IOfferRepository';
import { OfferRepository } from '../repositories/implementations/OfferRepository';
import { IOfferService } from '../services/interfaces/IOfferService';
import { OfferService } from '../services/implementations/OfferService';
import { IOfferPdfService } from '../services/interfaces/IOfferPdfService';
import { OfferPdfService } from '../services/implementations/OfferPdfService';
import { OfferController } from '../controllers/OfferController';
import { IATSService } from '../services/interfaces/IATSService';
import { ResumeParserService } from '../services/implementations/ResumeParserService';
import { GrokATSService } from '../services/implementations/GrokATSService';
import { ATSController } from '../controllers/ATSController';
import { ICompanyServiceClient } from '../services/interfaces/ICompanyServiceClient';
import { CompanyServiceClient } from '../services/implementations/CompanyServiceClient';
import { ICompanyOfferTemplateRepository } from '../repositories/interfaces/ICompanyOfferTemplateRepository';
import { CompanyOfferTemplateRepository } from '../repositories/implementations/CompanyOfferTemplateRepository';
import { ICompanyOfferTemplateService } from '../services/interfaces/ICompanyOfferTemplateService';
import { CompanyOfferTemplateService } from '../services/implementations/CompanyOfferTemplateService';
import { CompanyOfferTemplateController } from '../controllers/CompanyOfferTemplateController';
import { TYPES } from './types';

const container = new Container();

process.env.DATABASE_URL = process.env.DATABASE_URL || 'postgresql://postgres:devan@localhost:5432/application_service_db';

container.bind<PrismaClient>(TYPES.PrismaClient).toConstantValue(new PrismaClient());
container.bind<IApplicationRepository>(TYPES.IApplicationRepository).to(ApplicationRepository);
container.bind<IApplicationService>(TYPES.IApplicationService).to(ApplicationService);
container.bind<IEventService>(TYPES.IEventService).to(KafkaEventService);
container.bind<StatusUpdateService>(TYPES.StatusUpdateService).to(StatusUpdateService);
container.bind<ApplicationController>(TYPES.ApplicationController).to(ApplicationController);
container.bind<IInterviewRepository>(TYPES.IInterviewRepository).to(InterviewRepository);
container.bind<IInterviewService>(TYPES.IInterviewService).to(InterviewService);
container.bind<InterviewController>(TYPES.InterviewController).to(InterviewController);
container.bind<IUserServiceClient>(TYPES.IUserServiceClient).to(UserServiceClient);
container.bind<IJobServiceClient>(TYPES.IJobServiceClient).to(JobServiceClient);
container.bind<IOfferRepository>(TYPES.IOfferRepository).to(OfferRepository);
container.bind<IOfferService>(TYPES.IOfferService).to(OfferService);
container.bind<IOfferPdfService>(TYPES.IOfferPdfService).to(OfferPdfService);
container.bind<OfferController>(TYPES.OfferController).to(OfferController);
container.bind<ResumeParserService>(TYPES.ResumeParserService).to(ResumeParserService);
container.bind<GrokATSService>(TYPES.GrokATSService).to(GrokATSService);
container.bind<ATSController>(TYPES.ATSController).to(ATSController);
container.bind<ICompanyServiceClient>(TYPES.ICompanyServiceClient).to(CompanyServiceClient);
container.bind<ICompanyOfferTemplateRepository>(TYPES.ICompanyOfferTemplateRepository).to(CompanyOfferTemplateRepository);
container.bind<ICompanyOfferTemplateService>(TYPES.ICompanyOfferTemplateService).to(CompanyOfferTemplateService);
container.bind<CompanyOfferTemplateController>(TYPES.CompanyOfferTemplateController).to(CompanyOfferTemplateController);

export { container };