export const TYPES = {
  IApplicationService: Symbol.for('IApplicationService'),
  IApplicationRepository: Symbol.for('IApplicationRepository'),
  ApplicationController: Symbol.for('ApplicationController'),
  PrismaClient: Symbol.for('PrismaClient'),
  IEventService: Symbol.for('IEventService'),
  StatusUpdateService: Symbol.for('StatusUpdateService'),
  IInterviewService: Symbol.for('IInterviewService'),
  IInterviewRepository: Symbol.for('IInterviewRepository'),
  InterviewController: Symbol.for('InterviewController'),
  IUserServiceClient: Symbol.for('IUserServiceClient'),
  IJobServiceClient: Symbol.for('IJobServiceClient'),
  IOfferRepository: Symbol.for('IOfferRepository'),
  IOfferService: Symbol.for('IOfferService'),
  IOfferPdfService: Symbol.for('IOfferPdfService'),
  OfferController: Symbol.for('OfferController'),
  IATSService: Symbol.for('IATSService'),
  ResumeParserService: Symbol.for('ResumeParserService'),
  GrokATSService: Symbol.for('GrokATSService'),
  ATSController: Symbol.for('ATSController'),
  ICompanyServiceClient: Symbol.for('ICompanyServiceClient'),
  ICompanyOfferTemplateRepository: Symbol.for('ICompanyOfferTemplateRepository'),
  ICompanyOfferTemplateService: Symbol.for('ICompanyOfferTemplateService'),
  CompanyOfferTemplateController: Symbol.for('CompanyOfferTemplateController'),
  CloudinaryService: Symbol.for('CloudinaryService'),
};