export const AppConfig = {
  PORT: process.env.PORT,
  FRONTEND_URL: process.env.FRONTEND_URL,
  LOKI_HOST: process.env.LOKI_HOST,
  JOB_SUGGESTION_MIN_LIMIT: Number(process.env.JOB_SUGGESTION_MIN_LIMIT),
  JOB_SUGGESTION_MAX_LIMIT: Number(process.env.JOB_SUGGESTION_MAX_LIMIT),
  SUBSCRIPTION_SERVICE_URL: process.env.SUBSCRIPTION_SERVICE_URL,
};

