const TYPES = {
  UserService: Symbol.for('UserService'),
  IUserService: Symbol.for('IUserService'),
  UserRepository: Symbol.for('UserRepository'),
  IUserRepository: Symbol.for('IUserRepository'),
  EmailService: Symbol.for('EmailService'),
  UserController: Symbol.for('UserController'),
  AdminRepository: Symbol.for('AdminRepository'),
  IAdminRepository: Symbol.for('IAdminRepository'),
  AdminService: Symbol.for('AdminService'),
  IAdminService: Symbol.for('IAdminService'),
  AdminController: Symbol.for('AdminController'),
  ProfileRepository: Symbol.for('ProfileRepository'),
  IProfileRepository: Symbol.for('IProfileRepository'),
  ProfileService: Symbol.for('ProfileService'),
  IProfileService: Symbol.for('IProfileService'),
  ProfileController: Symbol.for('ProfileController'),
  ResumeController: Symbol.for('ResumeController'),
  ResumeService: Symbol.for('ResumeService'),
  IResumeService: Symbol.for('IResumeService'),
  IResumeRepository: Symbol.for('IResumeRepository'),
  AchievementService: Symbol.for('AchievementService'),
  IAchievementService: Symbol.for('IAchievementService'),
  AchievementRepository: Symbol.for('AchievementRepository'),
  IAchievementRepository: Symbol.for('IAchievementRepository'),
  AchievementController: Symbol.for('AchievementController'),
  CertificationService: Symbol.for('CertificationService'),
  ICertificationService: Symbol.for('ICertificationService'),
  CertificationRepository: Symbol.for('CertificationRepository'),
  ICertificationRepository: Symbol.for('ICertificationRepository'),
  CertificationController: Symbol.for('CertificationController'),
  CompanyApiRepository: Symbol.for('CompanyApiRepository'),
  ICompanyApiRepository: Symbol.for('ICompanyApiRepository'),
  RedisService: Symbol.for('RedisService'),
  JWTService: Symbol.for('JWTService'),
  CookieService: Symbol.for('CookieService'),
};

export default TYPES;