import { Container } from 'inversify';
import { INotificationRepository } from '../repositories/interfaces/INotificationRepository';
import { NotificationRepository } from '../repositories/implementations/NotificationRepository';
import { INotificationService } from '../services/interfaces/INotificationService';
import { NotificationService } from '../services/implementations/NotificationService';
import { NotificationController } from '../controllers/NotificationController';
import { IEventService } from '../services/interfaces/IEventService';
import { EventService } from '../services/implementations/EventService';
import { JobServiceClient } from '../services/implementations/JobServiceClient';
import { NotificationModel } from '../models/NotificationModel';
import { TYPES } from './types';

const container = new Container();
container.bind<INotificationRepository>(TYPES.INotificationRepository).to(NotificationRepository).inSingletonScope();
container.bind<INotificationService>(TYPES.INotificationService).to(NotificationService).inSingletonScope();
container.bind<NotificationController>(TYPES.INotificationController).to(NotificationController).inSingletonScope();
container.bind<IEventService>(TYPES.IEventService).to(EventService).inSingletonScope();
container.bind<JobServiceClient>(TYPES.JobServiceClient).to(JobServiceClient);
container.bind(TYPES.NotificationModel).toConstantValue(NotificationModel);
export { container };